version: '3.9'
networks:
  devops:
    driver: overlay
    ipam:
      driver: default

services:
    postgres:
        image: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        # volumes: 
        #   - ./postgres-data:/var/lib/postgresql/data
        #   # copy the sql script to create tables
        #   - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    dotnetapi:
        build: ./AspDotNet/Api6/
        ports:
          - "5005:80"
        depends_on:
          - postgres
        restart: always
    blazor:
        build: ./AspDotNet/BlazorWasm/
        ports:
          - "3000:80"