version: '3.9'
networks:
  devops:
    driver: overlay
    ipam:
      driver: default

services:
    dotnet:
        image: wasm:0.4
        ports:
          - target: 80
            published: 5006
            mode: host
        deploy:
          replicas: 1