# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import wordSplit_pb2 as wordSplit__pb2


class WordSplitterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSplitted = channel.unary_unary(
                '/WordSplitter/GetSplitted',
                request_serializer=wordSplit__pb2.OriginString.SerializeToString,
                response_deserializer=wordSplit__pb2.KeyWords.FromString,
                )
        self.SayHello = channel.unary_unary(
                '/WordSplitter/SayHello',
                request_serializer=wordSplit__pb2.HelloRequest.SerializeToString,
                response_deserializer=wordSplit__pb2.HelloReply.FromString,
                )


class WordSplitterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSplitted(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WordSplitterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSplitted': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSplitted,
                    request_deserializer=wordSplit__pb2.OriginString.FromString,
                    response_serializer=wordSplit__pb2.KeyWords.SerializeToString,
            ),
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=wordSplit__pb2.HelloRequest.FromString,
                    response_serializer=wordSplit__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WordSplitter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WordSplitter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSplitted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WordSplitter/GetSplitted',
            wordSplit__pb2.OriginString.SerializeToString,
            wordSplit__pb2.KeyWords.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WordSplitter/SayHello',
            wordSplit__pb2.HelloRequest.SerializeToString,
            wordSplit__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
