version: '3.9'
networks:
  devops:
    driver: overlay
    ipam:
      driver: default
services:
    buildkite:
        image: buildkite/agent
        environment:
          BUILDKITE_AGENT_TOKEN: "33144a98cf913f0d502b9d4be5af1cb2c5e607b311c5d42dfd"
        volumes: 
           - /var/run/docker.sock:/var/run/docker.sock
        deploy:
          replicas: 1