version: '3.9'
networks:
  devops:
    driver: overlay
    ipam:
      driver: default
services:
    postgres:
        image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD_FILE: /run/secrets/db_password
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
           - psqldb:/var/lib/postgresql/data
        #   # copy the sql script to create tables
        #   - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        deploy:
          replicas: 1
          placement: 
            constraints:
              - node.role == manager
        secrets:
          - db_password
volumes:
  psqldb:
    name: mypsqldbdata

secrets:
   db_password:
     file: ./Secrets/db_password.env