version: '3.9'
networks:
  devops:
    driver: overlay
    ipam:
      driver: default
services:
    postgres:
        image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD_FILE: /run/secrets/db_password
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - target: 5432
            published: 5432
            mode: host
        volumes: 
           - psqldb:/var/lib/postgresql/data
        deploy:
          replicas: 1
        secrets:
          - db_password
volumes:
  psqldb:
    name: mypsqldbdata

secrets:
   db_password:
     file: ./Secrets/db_password.env